Update dependencies 2024-05-16
exasol/bucketfs-python pull request #134
Opened 2024-05-16 14:00 UTC by Nicoretti

- **Update dependencies**
- **Update github workflows**
- **Update changelog**

### Submission Checklist

* [ ] Bumped version number
* [ ] Updated Documentation
* [ ] Updated API Documentation
* [ ] Updated the changelog

2024-05-16 15:01 UTC, kaklakariada requested changes

2024-05-16 18:57 UTC, Nicoretti commented on .github/workflows/build-and-publish.yml
> +        uses: actions/checkout@v3
Sadly this is not as trivial: https://github.com/exasol/python-toolbox/issues/181

2024-05-16 18:59 UTC, Nicoretti commented on .github/workflows/checks.yml
> +        exasol-version: ["7.1.9"]
One needs to check the used itde version if thats possible. Still see the point but it also should a task/issue on it's own.

2024-05-17 05:17 UTC, kaklakariada commented on .github/workflows/build-and-publish.yml
> +        uses: actions/checkout@v3
The ticket mentions `actions/upload-artifact`, this is about `actions/checkout`. But if that's a problem it's fine.

2024-05-17 07:57 UTC, Nicoretti commented on .github/workflows/build-and-publish.yml
> +        uses: actions/checkout@v3
good point, my bad ... context switching gone wrong :sweat_smile:

2024-05-17 09:55 UTC, Nicoretti commented on .github/workflows/checks.yml
> +        exasol-version: ["7.1.9"]
This should be fixed in the `exasol-toolbox` which is providing those workflows, I've created an issue for that, see https://github.com/exasol/python-toolbox/issues/184

2024-05-17 09:55 UTC, Nicoretti commented on .github/workflows/build-and-publish.yml
> +    runs-on: ubuntu-latest
This should be fixed in the `exasol-toolbox` which is providing those workflows, I've created an issue for that, see https://github.com/exasol/python-toolbox/issues/184

2024-05-17 12:18 UTC, kaklakariada approved these changes

2024-05-17 12:19 UTC, merged