#144: Added comment on using fixtures from pytest-plugin pytest-exas…
exasol/bucketfs-python pull request #145
Opened 2024-06-13 13:06 UTC by ckunki

Closes #144

2024-06-13 14:18 UTC, kaklakariada requested changes

2024-06-13 14:18 UTC, kaklakariada commented on test_saas/integration/contest.py
> +# Additionall fixtures provided by pytest-plugin pytest_exasol_saas
```suggestion
# Additional fixtures provided by pytest-plugin pytest_exasol_saas
```

2024-06-13 14:18 UTC, kaklakariada commented on test_saas/integration/contest.py
Rename to `context.py`?

2024-06-13 15:00 UTC, ckunki commented on test_saas/integration/contest.py
:rofl: - No I meant `conftest.py`

2024-06-14 06:59 UTC, kaklakariada approved these changes

2024-06-14 11:57 UTC, merged